const db = require('../db')
const { Book, Movie, Review } = require('../models')

db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
  const createMovies = [
    {
      movie_title: 'Little Women (2019)',
      movie_img: '/images/',
      year_released: 2019,
      actors: ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh', 'Timothée Chalamet'],
      director: 'Greta Gerwig',
      rating: 'PG',
      run_time: '2h 15m',
      imdb: '7.8/10',
      rotten_tomatoes: '95%',
      would_watch_again: yes,
      // related_book: { }
      // favorites: 5,
    },
    {
      movie_title: 'Little Women (1994)',
      movie_img: '/images/',
      year_released: 1994,
      actors: ['Susan Sarandon', 'Winona Ryder', 'Kirsten Dunst'],
      director: 'Gillian Armstrong',
      rating: 'PG',
      run_time: '1h 55m',
      imdb: '7.3/10',
      rotten_tomatoes: '93%',
      would_watch_again: yes,
      // favorites: 5,
    },
    // {
    //   movie_title: '',
    //   movie_img: '/images/',
    //   year_released: ,
    //   actors: [],
    //   director: '',
    //   rating: '',
    //   run_time: '',
    //   imdb: '',
    //   rotten_tomatoes: '',
    //   would_watch_again: true,
    //   favorites: 5,
    // },
    // {
    //   movie_title: '',
    //   movie_img: '/images/',
    //   year_released: ,
    //   actors: [],
    //   director: '',
    //   rating: '',
    //   run_time: '',
    //   imdb: '',
    //   rotten_tomatoes: '',
    //   would_watch_again: true,
    //   favorites: 5,
    // },
    // {
    //   movie_title: '',
    //   movie_img: '/images/',
    //   year_released: ,
    //   actors: [],
    //   director: '',
    //   rating: '',
    //   run_time: '',
    //   imdb: '',
    //   rotten_tomatoes: '',
    //   would_watch_again: true,
    //   favorites: 5,
    // },
    // {
    //   movie_title: '',
    //   movie_img: '/images/',
    //   year_released: ,
    //   actors: [],
    //   director: '',
    //   rating: '',
    //   run_time: '',
    //   imdb: '',
    //   rotten_tomatoes: '',
    //   would_watch_again: true,
    //   favorites: 5,
    // },
  ]
}